### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pommesbude1** [androidseb25/IPv64-iOS#10]
"Hi wie wäre es eine Option einzubauen um die App per FaceID, TouchID oder Pin zu sperren / entsperren? ( So wie bei WhatsApp ) 
und für die Widgets, falls noch nicht da, diese auf dem Lockscreen anzeigen zu lassen."

**Comment by androidseb25** [comment]
wieder auf gemacht und als Future Integration gelabelt

**Comment by androidseb25** [comment]
aufgesplittet zur besseren Implementierung der Features 

#12 - FaceID/TouchID/PIN 
#13 - Lockscreen Widgets
