### ISSUE TITLE
Log Ansicht

### ISSUE THREAD

**Issue by kallemarc** [androidseb25/IPv64-iOS#26]
Hallo,

es wäre wünschenswert, wenn man sich die Logs anschaut, in der App einen Eintrag antippen kann und von diesem Eintrag denn vollen Inhalt lesen kann, zudem wäre es super, da die API (GET /api?get_logs) 100 Einträge ausgibt, hier auch alles anzuzeigen, was vorhanden ist.

**Comment by androidseb25** [comment]
Hi kallemarc, 

das ist im neuen Update geplant :)

**Comment by androidseb25** [comment]
ist eingearbeitet kommt im Update 1.2 für iOS

<img src="https://github.com/androidseb25/IPv64-iOS/assets/11179091/f6c19f5b-e0a1-4a41-afbd-c2e1d0df089b" data-canonical-src="https://github.com/androidseb25/IPv64-iOS/assets/11179091/f6c19f5b-e0a1-4a41-afbd-c2e1d0df089b" width="200" height="400" alt="Log Ansicht 10" />

<img src="https://github.com/androidseb25/IPv64-iOS/assets/11179091/0bddca03-9a24-486a-b094-72de3fa5819c" data-canonical-src="https://github.com/androidseb25/IPv64-iOS/assets/11179091/0bddca03-9a24-486a-b094-72de3fa5819c" width="200" height="400" alt="Log Ansicht 100 (hab nur 36 Logs gehabt" />
