### ISSUE TITLE
Beta ausgelaufen

### ISSUE THREAD

**Issue by kallemarc** [androidseb25/IPv64-iOS#32]
Hallo, 

die Beta ist ausgelaufen und muss verlängert werden.

Viele Grüße

**Comment by androidseb25** [comment]
Ich weiß bin noch bis nächste Woche im Urlaub und verlängere dann sofort

**Comment by dagee** [comment]
Erst wenn man es nicht hat, merkt man wie gut es ist ;-)
Danke für die Entwicklungsarbeit!

**Comment by androidseb25** [comment]
Noch 2 Tage Geduld Sonntag Abend sollte es dann soweit sein

**Comment by androidseb25** [comment]
sollte nach der Prüfung von apple heute wieder verfügbar sein
